"""Hybrid masking: stochastic mixture of sub-strategies with optional curriculum.

Implements a meta-strategy that holds instances of registered sub-strategies
and delegates to them per-sample based on a mixture distribution. Supports:
  - Static mode: fixed policy_weights throughout training
  - Curriculum mode: step-based schedule with linear interpolation between breakpoints

Each sample's mask is generated by exactly one sub-strategy, sampled from the
mixture. Sub-strategies unavailable for a given sample (due to missing metadata)
are excluded from that sample's mixture and weights are re-normalized.
"""

from __future__ import annotations

import logging
from collections import OrderedDict
from typing import Any

import torch
from transformers import PreTrainedTokenizerBase

from masking.base import BaseMaskingStrategy, get_strategy, register_strategy

logger = logging.getLogger(__name__)

# Metadata keys required by each strategy. Strategies not listed require nothing.
# For "structure", the requirement is disjunctive (needs at least one).
STRATEGY_REQUIRED_METADATA: dict[str, set[str]] = {
    "uniform": set(),
    "span": set(),
    "cdr": {"cdr_mask"},
    "structure": {"knn_indices", "coords_ca"},
    "interface": {"paratope_labels"},
    "germline": {"germline_labels"},
    "multispecific": {"module_ids", "chain_type_ids"},
    # Intersection masker checks its own priors at runtime; the hybrid
    # outer layer only needs to confirm that the metadata dict is non-None
    # so the inner masker has a chance to fall back gracefully.
    "intersection": set(),
}


def _strategy_available(name: str, metadata: dict[str, torch.Tensor] | None) -> bool:
    """Check whether a strategy's required metadata is present in this sample."""
    required = STRATEGY_REQUIRED_METADATA.get(name, set())
    if not required:
        return True
    if metadata is None:
        return False
    # Structure needs at least one of knn_indices or coords_ca
    if name == "structure":
        return ("knn_indices" in metadata) or ("coords_ca" in metadata)
    # All others: every required key must be present
    return all(k in metadata for k in required)


@register_strategy("hybrid")
class HybridMasking(BaseMaskingStrategy):
    """Stochastic mixture of sub-strategies with optional curriculum scheduling.

    Per sample, one sub-strategy is sampled from the mixture distribution and
    used to generate the mask. Sub-strategies whose required metadata is absent
    are excluded from that sample's distribution.

    Args (via masking.params in YAML):
        sub_strategies: Names of sub-strategies to include.
        policy_weights: Initial mixture weights (same length as sub_strategies).
        sub_strategy_params: Per-sub-strategy kwargs, keyed by strategy name.
        curriculum: Optional list of {step, weights} breakpoints for scheduling.
    """

    def __init__(
        self,
        tokenizer: PreTrainedTokenizerBase,
        mask_prob: float = 0.15,
        mask_token_ratio: float = 0.8,
        random_token_ratio: float = 0.1,
        sub_strategies: list[str] | None = None,
        policy_weights: list[float] | None = None,
        sub_strategy_params: dict[str, dict[str, Any]] | None = None,
        curriculum: list[dict[str, Any]] | None = None,
        sampling_mode: str = "per_sample",
        adaptive: bool = False,
        adaptive_decay: float = 0.99,
        adaptive_temperature: float = 1.0,
        **kwargs: Any,
    ) -> None:
        super().__init__(
            tokenizer=tokenizer,
            mask_prob=mask_prob,
            mask_token_ratio=mask_token_ratio,
            random_token_ratio=random_token_ratio,
            **kwargs,
        )

        if sub_strategies is None:
            sub_strategies = ["uniform", "cdr", "span"]

        n = len(sub_strategies)
        if n == 0:
            raise ValueError("sub_strategies must contain at least one strategy")

        if policy_weights is None:
            policy_weights = [1.0] * n
        if len(policy_weights) != n:
            raise ValueError(
                f"policy_weights length {len(policy_weights)} != "
                f"sub_strategies length {n}"
            )

        self._strategy_names: list[str] = list(sub_strategies)
        self._base_weights = torch.tensor(policy_weights, dtype=torch.float)
        self._base_weights = self._base_weights / self._base_weights.sum()
        # IMPORTANT: _current_weights is in shared memory so DataLoader worker
        # processes (which inherit a copy of this strategy at fork time) see
        # curriculum updates from HybridMaskingCallback.set_step() which runs
        # in the main process. Without share_memory_, the curriculum is a
        # silent no-op whenever dataloader_num_workers > 0.
        self._current_weights = self._base_weights.clone().share_memory_()

        # Parse curriculum schedule
        self._curriculum: list[tuple[int, torch.Tensor]] | None = None
        if curriculum is not None:
            self._curriculum = []
            for entry in sorted(curriculum, key=lambda e: e["step"]):
                step = entry["step"]
                weights = torch.tensor(entry["weights"], dtype=torch.float)
                if len(weights) != n:
                    raise ValueError(
                        f"Curriculum weights at step {step} have length "
                        f"{len(weights)}, expected {n}"
                    )
                weights = weights / weights.sum()
                self._curriculum.append((step, weights))

        # Instantiate sub-strategies via registry
        sub_params = sub_strategy_params or {}
        self._strategies: OrderedDict[str, BaseMaskingStrategy] = OrderedDict()
        for name in self._strategy_names:
            params = sub_params.get(name, {})
            self._strategies[name] = get_strategy(
                name,
                tokenizer=tokenizer,
                mask_prob=mask_prob,
                mask_token_ratio=mask_token_ratio,
                random_token_ratio=random_token_ratio,
                **params,
            )

        # Sampling mode: per_sample (default) draws one sub-strategy per
        # forward call (i.e. per sample, since the collator dispatches per
        # sequence). per_batch draws one sub-strategy per forward batch, so
        # all samples in a batch share the same inductive bias and the
        # gradient is a "pure" specialist signal that step.
        if sampling_mode not in ("per_sample", "per_batch"):
            raise ValueError(
                f"sampling_mode must be 'per_sample' or 'per_batch', got {sampling_mode!r}"
            )
        self._sampling_mode = sampling_mode
        self._batch_strategy_index: int | None = None

        # Adaptive (self-paced) curriculum: track per-strategy EMA of recent
        # loss; choose the strategy whose tracked loss is highest so the
        # model spends gradient budget on its weak spots. Disabled by
        # default (deterministic curriculum behavior).
        self._adaptive = adaptive
        self._adaptive_decay = float(adaptive_decay)
        self._adaptive_temperature = float(adaptive_temperature)
        self._loss_ema = torch.full(
            (n,), float("nan"), dtype=torch.float,
        ).share_memory_()
        # Last-sampled strategy index per call, used so an external
        # callback can attribute a loss back to the correct sub-strategy.
        self._last_strategy_index = torch.full(
            (1,), -1, dtype=torch.long,
        ).share_memory_()

        # Diagnostics
        self._total_calls = 0
        self._strategy_counts: dict[str, int] = {n: 0 for n in self._strategy_names}
        self._fallback_count = 0
        self._current_step = 0
        self._log_interval = 1000

        logger.info(
            "HybridMasking initialized with %d sub-strategies: %s",
            n, self._strategy_names,
        )
        logger.info(
            "sampling_mode=%s, adaptive=%s",
            self._sampling_mode, self._adaptive,
        )
        logger.info(
            "Initial weights: %s",
            dict(zip(self._strategy_names, self._base_weights.tolist())),
        )
        if self._curriculum:
            logger.info(
                "Curriculum schedule with %d breakpoints",
                len(self._curriculum),
            )

    def set_step(self, step: int) -> None:
        """Update mixture weights based on curriculum schedule.

        Called by HybridMaskingCallback.on_step_begin(). No-op in static mode.

        IMPORTANT: writes are in-place via copy_() so the underlying shared
        memory is mutated. Reassigning self._current_weights would create a
        new tensor that's NOT shared with the forked DataLoader workers.
        """
        self._current_step = step
        if self._curriculum is None:
            return

        schedule = self._curriculum

        # Compute the new weights for this step
        if step <= schedule[0][0]:
            new_weights = schedule[0][1]
        elif step >= schedule[-1][0]:
            new_weights = schedule[-1][1]
        else:
            new_weights = None
            for i in range(len(schedule) - 1):
                s0, w0 = schedule[i]
                s1, w1 = schedule[i + 1]
                if s0 <= step < s1:
                    alpha = (step - s0) / (s1 - s0)
                    new_weights = (1 - alpha) * w0 + alpha * w1
                    new_weights = new_weights / new_weights.sum()
                    break
            if new_weights is None:
                return

        # In-place write to the shared-memory tensor.
        self._current_weights.copy_(new_weights)

    def begin_batch(self) -> None:
        """Hook called by the collator at the start of every batch.

        In per_batch sampling mode this draws the single strategy that all
        samples in the batch will share. No-op in per_sample mode.
        """
        if self._sampling_mode != "per_batch":
            self._batch_strategy_index = None
            return
        # Sample once per batch. We don't know yet which sub-strategies
        # have metadata (depends on the samples), so we pick from the full
        # weight vector and rely on per-sample fallback when a sample is
        # missing the chosen strategy's metadata.
        weights = self._effective_policy_weights().clone()
        if (weights <= 0).all():
            self._batch_strategy_index = 0
        else:
            weights = weights / weights.sum()
            self._batch_strategy_index = int(torch.multinomial(weights, 1).item())

    def update_loss(self, strategy_index: int, loss: float) -> None:
        """Update the per-strategy loss EMA from a training callback.

        Used by the adaptive sampler. Called after the model produces a
        loss for a batch tagged with which sub-strategy generated it.
        """
        if not self._adaptive:
            return
        if not (0 <= strategy_index < len(self._strategy_names)):
            return
        prev = self._loss_ema[strategy_index].item()
        if prev != prev:  # NaN check — first observation
            self._loss_ema[strategy_index] = float(loss)
        else:
            self._loss_ema[strategy_index] = (
                self._adaptive_decay * prev
                + (1 - self._adaptive_decay) * float(loss)
            )

    def _effective_policy_weights(self) -> torch.Tensor:
        """Return the policy weights to use for this step, before per-sample
        availability filtering."""
        if not self._adaptive:
            return self._current_weights
        # Adaptive mode: blend the curriculum policy with a softmax over
        # per-strategy loss EMAs, so we shift gradient toward strategies
        # the model is currently struggling with. Strategies that haven't
        # been seen yet get NaN -> treat as max so they get explored.
        ema = self._loss_ema.clone()
        seen = ~torch.isnan(ema)
        if not seen.any():
            return self._current_weights
        # Replace NaN with max-seen-loss + small bonus to encourage exploration
        max_seen = ema[seen].max() if seen.any() else 1.0
        ema = torch.where(seen, ema, max_seen + 0.5)
        # Softmax over scaled losses
        scaled = ema / max(self._adaptive_temperature, 1e-6)
        scaled = scaled - scaled.max()  # stabilize
        soft = torch.softmax(scaled, dim=0)
        # Multiplicatively combine with curriculum weights
        combined = self._current_weights * soft
        if combined.sum() <= 0:
            return self._current_weights
        return combined / combined.sum()

    def select_mask_positions(
        self,
        input_ids: torch.Tensor,
        special_tokens_mask: torch.Tensor,
        metadata: dict[str, torch.Tensor] | None = None,
    ) -> torch.Tensor:
        self._total_calls += 1

        # Filter to available sub-strategies for this sample
        eff_weights = self._effective_policy_weights()
        available_indices = []
        available_weights = []
        for i, name in enumerate(self._strategy_names):
            if _strategy_available(name, metadata):
                available_indices.append(i)
                available_weights.append(eff_weights[i].item())

        # Fallback: no strategy available (shouldn't happen if uniform is included)
        if not available_indices:
            self._fallback_count += 1
            probability_matrix = torch.full(input_ids.shape, self.mask_prob)
            probability_matrix[special_tokens_mask.bool()] = 0.0
            return torch.bernoulli(probability_matrix).bool()

        # Sample one sub-strategy
        if (
            self._sampling_mode == "per_batch"
            and self._batch_strategy_index is not None
            and self._batch_strategy_index in available_indices
        ):
            strategy_index = self._batch_strategy_index
        else:
            weights_tensor = torch.tensor(available_weights, dtype=torch.float)
            wsum = weights_tensor.sum()
            if wsum <= 0:
                strategy_index = available_indices[0]
            else:
                weights_tensor = weights_tensor / wsum
                selected_idx = torch.multinomial(weights_tensor, 1).item()
                strategy_index = available_indices[selected_idx]
        strategy_name = self._strategy_names[strategy_index]

        self._strategy_counts[strategy_name] += 1
        self._last_strategy_index[0] = strategy_index

        # Periodic logging
        if self._total_calls % self._log_interval == 0:
            logger.info(
                "HybridMasking step=%d: counts=%s (fallback=%d / %d total)",
                self._current_step,
                self._strategy_counts,
                self._fallback_count,
                self._total_calls,
            )
            if self._curriculum:
                logger.info(
                    "Current weights: %s",
                    dict(zip(
                        self._strategy_names,
                        self._current_weights.tolist(),
                    )),
                )

        # Delegate to selected sub-strategy
        return self._strategies[strategy_name].select_mask_positions(
            input_ids, special_tokens_mask, metadata=metadata,
        )
