"""Measure overlap between the OAS pretraining corpus and every benchmark set.

This is contamination "axis 2" from wiki/10-rebuttal-notes.md §2 — the one axis
the repo never measured, and the one place reviewers can legitimately say we did
not do the work:

    #2.5.2 "Are evaluation proteins clustered away from OAS pretraining
            sequences and from data used to train the paratope and IgFold
            teachers?"

Axes 1, 3 and 4 (OAS train/eval, teacher-train vs probe-test, within-benchmark
split quality) are answered elsewhere. This script answers only axis 2: do the
antibodies we evaluate on also appear in the 497k sequences we pretrained on?

WHY THE OBVIOUS METRIC IS THE WRONG ONE
---------------------------------------
Global percent identity is close to meaningless for antibody VH domains. Every
VH shares the same framework scaffold, so two *unrelated* human antibodies from
the same germline family routinely sit at 80-90% identity. A generic "cluster at
90% identity" audit — the MMseqs2 reflex — would therefore flag most of the
corpus against most of each benchmark and tell us nothing.

What distinguishes one antibody from another is CDR-H3: a 5-30 residue segment
generated by V(D)J recombination plus junctional diversity. Two antibodies
sharing an exact CDR-H3 are, essentially without exception, clonally related.
So this script reports a ladder of increasingly strict criteria:

    exact_vh        the full VH string appears verbatim in the corpus.
                    Unambiguous contamination.
    cdr3_exact      CDR-H3 appears verbatim among the corpus CDR-H3s.
                    Near-certain clonal relationship.
    cdr3_and_v      CDR-H3 match AND same V-gene family. The standard
                    approximate-clonotype definition; strictest evidence.
    max_identity    highest full-VH identity to ANY corpus sequence, found by
                    an 8-mer prefilter plus global alignment. Reported WITH the
                    germline background level below, which is what makes it
                    interpretable.
    background      median max_identity over benchmark antibodies whose CDR-H3
                    does NOT appear in the corpus. This is the "unrelated
                    antibody" floor. max_identity is only evidence of
                    contamination insofar as it exceeds this.

CDR-H3 DEFINITIONS ARE MATCHED ON BOTH SIDES
--------------------------------------------
The corpus carries OAS's own ``cdr3_aa`` annotation. Benchmark sequences are
numbered with ANARCI and CDR-H3 taken as IMGT positions 105-117. These two
definitions were verified identical on 300 randomly sampled corpus sequences
(300/300 exact agreement), so a CDR-H3 comparison across the two sides is
apples-to-apples rather than an artifact of differing conventions.

LIGHT CHAINS
------------
Pretraining is VH-only, so a light chain cannot be contaminated by this corpus.
The structural benchmarks (contact map, structure probe) contain both H and L
chains; ANARCI's chain_type separates them and light chains are reported
separately rather than silently diluting the heavy-chain rate.

Usage:
    PATH=$CONDA_PREFIX/bin:$PATH python scripts/contamination_audit.py
    python scripts/contamination_audit.py --max-identity-sample 4000

ANARCI needs ``hmmscan`` on PATH; it ships in the abmlm env's bin/ directory.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

logger = logging.getLogger(__name__)

AA = "ACDEFGHIKLMNPQRSTVWY"
AA_CODE = {c: i + 1 for i, c in enumerate(AA)}  # 0 reserved for pad/invalid
#: str.translate table -> C-speed encoding; anything non-standard maps to 0 and
#: any k-mer covering it is dropped.
_AA_TABLE = bytes(AA_CODE.get(chr(i), 0) for i in range(256))
KMER_K = 8
KMER_BITS = 5  # 21 symbols fit in 5 bits; k=8 -> 40 bits, fits in uint64

CORPUS_PATH = "data/processed/oas_vh_500k_annotated.jsonl"
OUT_DIR = Path("comparison_outputs")


# ---------------------------------------------------------------------------
# Corpus
# ---------------------------------------------------------------------------

def load_corpus(path: str) -> dict[str, Any]:
    """Load the pretraining corpus with its CDR-H3 and V-gene annotations.

    ``oas_vh_500k_annotated.jsonl`` is verified byte-identical in sequence and
    order to ``oas_vh_500k.jsonl``, the file the configs actually pretrain on,
    so its annotations describe exactly the pretraining set.
    """
    seqs: list[str] = []
    cdr3s: list[str] = []
    vgenes: list[str] = []
    with open(path) as f:
        for line in f:
            d = json.loads(line)
            seqs.append(d["sequence"])
            cdr3s.append(d.get("cdr3_aa") or "")
            vgenes.append((d.get("v_call") or "").split("*")[0])
    logger.info(
        "corpus: %d sequences, %d unique VH, %d unique CDR-H3",
        len(seqs), len(set(seqs)), len({c for c in cdr3s if c}),
    )
    return {"seqs": seqs, "cdr3s": cdr3s, "vgenes": vgenes}


# ---------------------------------------------------------------------------
# 8-mer index for nearest-neighbour prefiltering
# ---------------------------------------------------------------------------

class KmerIndex:
    """Sorted (kmer, sequence_id) index supporting top-N candidate lookup.

    Exists purely to avoid 497k full alignments per query. Two sequences at high
    identity share many exact 8-mers, so ranking corpus sequences by shared
    8-mer count and aligning only the top handful finds the true nearest
    neighbour at a tiny fraction of the cost.
    """

    def __init__(self, sequences: list[str], k: int = KMER_K) -> None:
        self.k = k
        logger.info("building %d-mer index over %d sequences", k, len(sequences))
        keys, ids = [], []
        for i, s in enumerate(sequences):
            codes = np.frombuffer(
                s.encode("ascii", "replace").translate(_AA_TABLE), dtype=np.uint8
            ).astype(np.uint64)
            enc = self._encode(codes, k)
            if enc.size:
                keys.append(enc)
                ids.append(np.full(enc.size, i, dtype=np.uint32))
        key_arr = np.concatenate(keys)
        id_arr = np.concatenate(ids)
        order = np.argsort(key_arr, kind="stable")
        self.keys = key_arr[order]
        self.ids = id_arr[order]
        logger.info("index: %d postings (%.1f MB)", self.keys.size,
                    (self.keys.nbytes + self.ids.nbytes) / 1e6)

    @staticmethod
    def _encode(codes: np.ndarray, k: int) -> np.ndarray:
        """Roll a sequence's amino-acid codes into packed uint64 k-mers."""
        n = codes.size - k + 1
        if n <= 0:
            return np.empty(0, dtype=np.uint64)
        out = np.zeros(n, dtype=np.uint64)
        valid = np.ones(n, dtype=bool)
        for t in range(k):
            window = codes[t : t + n]
            out |= window << np.uint64(KMER_BITS * t)
            valid &= window > 0  # drop k-mers spanning a non-standard residue
        return out[valid]

    def candidates(self, sequence: str, top_n: int) -> np.ndarray:
        """Return corpus ids sharing the most 8-mers with ``sequence``."""
        codes = np.frombuffer(
            sequence.encode("ascii", "replace").translate(_AA_TABLE), dtype=np.uint8
        ).astype(np.uint64)
        query = np.unique(self._encode(codes, self.k))
        if query.size == 0:
            return np.empty(0, dtype=np.int64)
        lo = np.searchsorted(self.keys, query, side="left")
        hi = np.searchsorted(self.keys, query, side="right")
        hits = [self.ids[a:b] for a, b in zip(lo, hi) if b > a]
        if not hits:
            return np.empty(0, dtype=np.int64)
        counts = np.bincount(np.concatenate(hits))
        n = min(top_n, counts.size)
        top = np.argpartition(counts, -n)[-n:]
        return top[np.argsort(counts[top])[::-1]]


# ---------------------------------------------------------------------------
# Identity
# ---------------------------------------------------------------------------

def make_aligner():
    from Bio import Align
    from Bio.Align import substitution_matrices

    aligner = Align.PairwiseAligner(mode="global")
    aligner.substitution_matrix = substitution_matrices.load("BLOSUM62")
    aligner.open_gap_score = -11
    aligner.extend_gap_score = -1
    # Free end gaps: benchmark chains are PDB-derived and often start or end a
    # few residues into the domain, which would otherwise be penalised as
    # internal gaps and understate identity.
    aligner.end_gap_score = 0.0
    return aligner


def percent_identity(aligner, a: str, b: str) -> float:
    """Percent identity over the length of the shorter sequence."""
    try:
        aln = aligner.align(a, b)[0]
    except Exception:  # pragma: no cover - degenerate sequences
        return 0.0
    ta, tb = aln[0], aln[1]
    matches = sum(1 for x, y in zip(ta, tb) if x == y and x != "-")
    return 100.0 * matches / max(1, min(len(a), len(b)))


# ---------------------------------------------------------------------------
# Benchmark sequence collection
# ---------------------------------------------------------------------------

def _tap_sequences() -> list[tuple[str, str]]:
    import pandas as pd
    from data.benchmarks.developability import _extract_vh

    df = pd.read_csv("data/tap.tab", sep="\t")
    out = []
    for _, row in df.iterrows():
        vh = _extract_vh(str(row["X"]))
        if vh:
            out.append((str(row["ID"]).strip('"'), vh))
    return out


def _paratope_sequences() -> list[tuple[str, str]]:
    import pickle

    df = pickle.load(open("data/sabdab_liberis.pkl", "rb"))
    col = "Antibody" if "Antibody" in df.columns else "X"
    return [(str(i), str(s)) for i, s in zip(df["ID"], df[col])]


def _ab_bind_sequences() -> list[tuple[str, str]]:
    """Wild-type chains only — mutants differ from these by a few residues."""
    from data.benchmarks.ab_bind import load_ab_bind

    seen: dict[tuple[str, str], str] = {}
    for r in load_ab_bind():
        seen.setdefault((r["pdb_id"], r["chain_id"]), r["wildtype_seq"])
    return [(f"{p}_{c}", s) for (p, c), s in seen.items()]


def _covabdab_sequences() -> list[tuple[str, str]]:
    from data.benchmarks.binding import _load_and_filter

    df = _load_and_filter(Path("data/covabdab/CoV-AbDab.csv"))
    return [(f"cov{i}", s) for i, s in enumerate(df["vh_sequence"])]


def _ngbriney_sequences() -> list[tuple[str, str]]:
    import pandas as pd

    df = pd.read_csv("data/ngbriney/E_hd-0_cov-1.csv")
    return [(str(n), str(s)) for n, s in zip(df["name"], df["h_sequence"])]


def _sabdab_struct_sequences() -> list[tuple[str, str]]:
    """Chains behind the contact-map and structure-probe benchmarks."""
    import torch

    entries = torch.load("data/structures/sabdab_liberis_coords.pt", weights_only=False)
    return [
        (f"{e['pdb_id']}_{e.get('chain_id', i)}", e["sequence"])
        for i, e in enumerate(entries)
    ]


BENCHMARKS: dict[str, Any] = {
    "paratope (SAbDab_Liberis)": _paratope_sequences,
    "developability (TAP)": _tap_sequences,
    "ab_bind (ddG)": _ab_bind_sequences,
    "binding (CoV-AbDab)": _covabdab_sequences,
    "binding (Ng&Briney E)": _ngbriney_sequences,
    "structure (SAbDab coords)": _sabdab_struct_sequences,
}


# ---------------------------------------------------------------------------
# ANARCI annotation
# ---------------------------------------------------------------------------

def annotate(sequences: list[str], ncpu: int = 8) -> list[dict[str, Any] | None]:
    """Return chain type, CDR-H3 (IMGT 105-117) and V gene for each sequence.

    The IMGT 105-117 span reproduces OAS's own ``cdr3_aa`` exactly (verified
    300/300 on corpus samples), which is what lets CDR-H3s be compared across
    the two sides at all.
    """
    from anarci import run_anarci

    # assign_germline=True is required — without it ANARCI omits the
    # ``germlines`` key entirely and every V gene silently comes back empty,
    # which would make the cdr3_and_v column vacuously zero rather than
    # informative.
    numbered, details = run_anarci(
        [(f"s{i}", s) for i, s in enumerate(sequences)],
        scheme="imgt", ncpu=ncpu, assign_germline=True,
    )[1:3]

    out: list[dict[str, Any] | None] = []
    for num, det in zip(numbered, details):
        if not num or not det:
            out.append(None)
            continue
        cdr3 = "".join(
            aa for (pos, _ins), aa in num[0][0] if 105 <= pos <= 117 and aa != "-"
        )
        d = det[0]
        out.append({
            "chain_type": d.get("chain_type"),
            "cdr3": cdr3,
            "v_gene": (d.get("germlines", {}).get("v_gene", [["", ""]])[0] or ["", ""])[1].split("*")[0],
            "species": (d.get("germlines", {}).get("v_gene", [["", ""]])[0] or ["", ""])[0],
        })
    return out


# ---------------------------------------------------------------------------
# Audit
# ---------------------------------------------------------------------------

def audit_benchmark(
    name: str,
    entries: list[tuple[str, str]],
    corpus: dict[str, Any],
    vh_set: set[str],
    cdr3_to_vgenes: dict[str, set[str]],
    index: KmerIndex,
    aligner,
    max_identity_sample: int,
    top_n: int,
    rng: np.random.Generator,
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    ids = [i for i, _ in entries]
    seqs = [s for _, s in entries]
    logger.info("[%s] %d sequences — running ANARCI", name, len(seqs))
    ann = annotate(seqs)

    rows: list[dict[str, Any]] = []
    for eid, seq, a in zip(ids, seqs, ann):
        chain = (a or {}).get("chain_type") or "?"
        cdr3 = (a or {}).get("cdr3") or ""
        vgene = (a or {}).get("v_gene") or ""
        cdr3_hit = bool(cdr3) and cdr3 in cdr3_to_vgenes
        rows.append({
            "benchmark": name,
            "id": eid,
            "chain_type": chain,
            "length": len(seq),
            "cdr3": cdr3,
            "cdr3_length": len(cdr3),
            "v_gene": vgene,
            "exact_vh": seq in vh_set,
            "cdr3_exact": cdr3_hit,
            "cdr3_and_v": cdr3_hit and vgene in cdr3_to_vgenes.get(cdr3, set()),
            "max_identity": None,
            "_seq": seq,
        })

    heavy = [r for r in rows if r["chain_type"] == "H"]

    # max_identity is the expensive metric. Compute it for every heavy chain
    # with a CDR-H3 hit (those are the candidate contamination cases and must
    # not be sampled away), plus a random sample of the rest to establish the
    # unrelated-antibody background.
    hits = [r for r in heavy if r["cdr3_exact"]]
    misses = [r for r in heavy if not r["cdr3_exact"]]
    budget = max(0, max_identity_sample - len(hits))
    if len(misses) > budget:
        picked = rng.choice(len(misses), size=budget, replace=False)
        misses = [misses[i] for i in picked]
    targets = hits + misses
    logger.info(
        "[%s] %d heavy chains; scoring identity for %d (%d CDR-H3 hits + %d sampled)",
        name, len(heavy), len(targets), len(hits), len(misses),
    )

    for j, r in enumerate(targets):
        cand = index.candidates(r["_seq"], top_n)
        best = 0.0
        for c in cand:
            best = max(best, percent_identity(aligner, r["_seq"], corpus["seqs"][int(c)]))
        r["max_identity"] = round(best, 2)
        if (j + 1) % 500 == 0:
            logger.info("[%s]   %d/%d aligned", name, j + 1, len(targets))

    scored_hits = [r["max_identity"] for r in hits if r["max_identity"] is not None]
    scored_miss = [r["max_identity"] for r in misses if r["max_identity"] is not None]

    summary = {
        "benchmark": name,
        "n_total": len(rows),
        "n_heavy": len(heavy),
        "n_light_or_unnumbered": len(rows) - len(heavy),
        "exact_vh": sum(1 for r in heavy if r["exact_vh"]),
        "cdr3_exact": len(hits),
        "cdr3_exact_pct": round(100.0 * len(hits) / max(1, len(heavy)), 2),
        "cdr3_and_v": sum(1 for r in heavy if r["cdr3_and_v"]),
        # Short CDR-H3s carry little information: the space of 5-mers is small
        # enough that an exact match against 497k sequences is expected by
        # chance. Reporting the hits' lengths keeps a raw count from being read
        # as stronger evidence than it is.
        "median_cdr3_len_hits": (
            round(float(np.median([r["cdr3_length"] for r in hits])), 1) if hits else None
        ),
        "median_cdr3_len_all": (
            round(float(np.median([r["cdr3_length"] for r in heavy])), 1) if heavy else None
        ),
        "median_identity_cdr3_hits": round(float(np.median(scored_hits)), 2) if scored_hits else None,
        "background_median_identity": round(float(np.median(scored_miss)), 2) if scored_miss else None,
        "max_identity_overall": round(max(scored_hits + scored_miss), 2) if (scored_hits or scored_miss) else None,
        "n_ge_95_identity": sum(1 for v in scored_hits + scored_miss if v >= 95),
        "n_identity_scored": len(scored_hits) + len(scored_miss),
    }
    for r in rows:
        r.pop("_seq", None)
    return summary, rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus", default=CORPUS_PATH)
    parser.add_argument(
        "--max-identity-sample", type=int, default=2000,
        help="Per benchmark, cap on how many heavy chains get a full identity "
             "search. CDR-H3 hits are always included; the cap applies to the "
             "background sample.",
    )
    parser.add_argument(
        "--top-n", type=int, default=25,
        help="Corpus candidates per query to align, ranked by shared 8-mers.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--out-dir", default=str(OUT_DIR))
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )

    # ANARCI shells out to hmmscan; it lives in the env's bin/ but is not
    # necessarily on PATH when the script is invoked by absolute interpreter.
    env_bin = str(Path(sys.executable).parent)
    if env_bin not in os.environ.get("PATH", ""):
        os.environ["PATH"] = env_bin + os.pathsep + os.environ.get("PATH", "")

    corpus = load_corpus(args.corpus)
    vh_set = set(corpus["seqs"])
    cdr3_to_vgenes: dict[str, set[str]] = defaultdict(set)
    for c, v in zip(corpus["cdr3s"], corpus["vgenes"]):
        if c:
            cdr3_to_vgenes[c].add(v)

    index = KmerIndex(corpus["seqs"])
    aligner = make_aligner()
    rng = np.random.default_rng(args.seed)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    summaries: list[dict[str, Any]] = []
    all_rows: list[dict[str, Any]] = []
    for name, loader in BENCHMARKS.items():
        try:
            entries = [(i, s) for i, s in loader() if s and len(s) >= 50]
        except Exception as e:
            logger.error("[%s] could not load: %s", name, e)
            continue
        if not entries:
            logger.warning("[%s] no sequences", name)
            continue
        summary, rows = audit_benchmark(
            name, entries, corpus, vh_set, cdr3_to_vgenes, index, aligner,
            args.max_identity_sample, args.top_n, rng,
        )
        summaries.append(summary)
        all_rows.extend(rows)
        logger.info("[%s] %s", name, json.dumps(summary))

    summary_path = out_dir / "contamination_audit.csv"
    with summary_path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(summaries[0].keys()))
        w.writeheader()
        w.writerows(summaries)
    logger.info("wrote %s", summary_path)

    detail_path = out_dir / "contamination_audit_per_sequence.csv"
    with detail_path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(all_rows[0].keys()))
        w.writeheader()
        w.writerows(all_rows)
    logger.info("wrote %s", detail_path)

    print("\n=== contamination audit (axis 2: benchmark vs OAS pretraining corpus) ===")
    for s in summaries:
        print(
            f"{s['benchmark']:<30} heavy={s['n_heavy']:>6}  "
            f"exact_VH={s['exact_vh']:>4}  "
            f"CDR-H3 in corpus={s['cdr3_exact']:>5} ({s['cdr3_exact_pct']:>5.1f}%)  "
            f"median id (hits)={s['median_identity_cdr3_hits']}  "
            f"background={s['background_median_identity']}"
        )


if __name__ == "__main__":
    main()
