"""Generate per-seed experiment configs for the pretraining seed replicates.

Reviewers #2, #5.1 and #6 all flagged that each strategy has exactly one
pretrained encoder, so the reported gaps cannot be separated from run-to-run
noise. This emits config variants that differ from their base config in
exactly two fields:

    seed:                     <the replicate seed>
    training.output_dir:      models/checkpoints/<name>_s<seed>

Everything else — including ``data.data_split_seed`` — is inherited, so the
held-out split is byte-identical across replicates (see ``data/splits.py``).
The experiment name must change because ``evaluation/compare.py`` discovers
runs by directory name; same-named runs would overwrite each other.

Usage:
    python scripts/make_seed_configs.py                  # seeds 1 and 2
    python scripts/make_seed_configs.py --seeds 1 2 3
    python scripts/make_seed_configs.py --dry-run
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from training.config import load_config

logger = logging.getLogger(__name__)

#: Non-hybrid strategies only. Hybrids are deferred — see wiki/10-rebuttal-notes.md §4.3.
#: ``runner`` selects the launch script: untrained is a random-init control that
#: is built directly rather than trained.
STRATEGIES: list[tuple[str, str, str]] = [
    # (base config,                                experiment name,               runner)
    ("configs/medium.yaml",                        "uniform_medium",              "train"),
    ("configs/cdr_medium.yaml",                    "cdr_medium",                  "train"),
    ("configs/span_medium.yaml",                   "span_medium",                 "train"),
    ("configs/structure_medium.yaml",              "structure_medium",            "train"),
    ("configs/structure_longrange_medium.yaml",    "structure_longrange_medium",  "train"),
    ("configs/interface_medium.yaml",              "interface_medium",            "train"),
    ("configs/germline_medium.yaml",               "germline_medium",             "train"),
    ("configs/intersection_medium.yaml",           "intersection_medium",         "train"),
    ("configs/untrained_medium.yaml",              "untrained_medium",            "untrained"),
]

_HEADER = """\
# GENERATED by scripts/make_seed_configs.py — do not edit by hand.
#
# Seed replicate of {base}
# Differs from the base config in exactly two fields:
#   seed:                {seed} (was {base_seed})
#   training.output_dir: {out_dir}
#
# data.data_split_seed is deliberately inherited (default 42) so this replicate
# trains and evaluates on the identical held-out split as every other run.
# Varying `seed` varies weight init and masking RNG only.
"""


def build_seed_config(base_path: Path, name: str, seed: int) -> tuple[dict, str]:
    """Return the (config dict, YAML text) for one replicate."""
    with base_path.open() as f:
        cfg = yaml.safe_load(f) or {}

    base_seed = cfg.get("seed", 42)
    cfg["seed"] = seed
    cfg.setdefault("training", {})["output_dir"] = f"models/checkpoints/{name}_s{seed}"

    header = _HEADER.format(
        base=base_path.as_posix(),
        seed=seed,
        base_seed=base_seed,
        out_dir=cfg["training"]["output_dir"],
    )
    body = yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False)
    return cfg, header + "\n" + body


def _verify(base_path: Path, new_path: Path, seed: int, name: str) -> None:
    """Assert the emitted config differs from base ONLY in the two fields."""
    base, new = load_config(base_path), load_config(new_path)

    assert new.seed == seed, f"{new_path}: seed is {new.seed}, expected {seed}"
    assert new.training.output_dir == f"models/checkpoints/{name}_s{seed}", (
        f"{new_path}: unexpected output_dir {new.training.output_dir}"
    )
    assert new.data.data_split_seed == base.data.data_split_seed == 42, (
        f"{new_path}: data_split_seed drifted — replicates must share a split"
    )

    # Every other field must be untouched.
    for section in ("data", "masking", "model"):
        assert vars(getattr(base, section)) == vars(getattr(new, section)), (
            f"{new_path}: {section} config drifted from base"
        )
    base_tr, new_tr = dict(vars(base.training)), dict(vars(new.training))
    base_tr.pop("output_dir"), new_tr.pop("output_dir")
    assert base_tr == new_tr, f"{new_path}: training config drifted from base"


def register_experiments(
    registry_path: Path, manifest: list[tuple[str, str, str]],
) -> int:
    """Add the replicates to configs/experiments.yaml, preserving its header.

    ``scripts/run_all_evaluations.py`` resolves ``--experiments <name>`` through
    this registry, so an unregistered replicate is silently un-evaluatable.
    Existing entries are never modified.
    """
    text = registry_path.read_text()
    header = "".join(
        line for line in text.splitlines(keepends=True)
        if line.startswith("#") or not line.strip()
    ).rstrip("\n")

    registry = yaml.safe_load(text) or {}
    experiments = registry.setdefault("experiments", {})

    added = 0
    for config, name, _runner in manifest:
        if name in experiments:
            continue
        experiments[name] = {
            "config": config,
            "checkpoint": f"models/checkpoints/{name}/final",
        }
        added += 1

    if added:
        body = yaml.safe_dump(registry, sort_keys=False, default_flow_style=False)
        registry_path.write_text(f"{header}\n\n{body}")
    return added


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--seeds", type=int, nargs="+", default=[1, 2],
        help="Replicate seeds to emit (default: 1 2). Seed 42 already exists.",
    )
    parser.add_argument("--out-dir", type=str, default="configs/seeds")
    parser.add_argument(
        "--dry-run", action="store_true", help="Print what would be written.",
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    repo = Path(__file__).resolve().parent.parent
    out_dir = repo / args.out_dir
    if not args.dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    manifest: list[tuple[str, str, str]] = []
    for base_rel, name, runner in STRATEGIES:
        base_path = repo / base_rel
        if not base_path.exists():
            raise FileNotFoundError(f"base config missing: {base_path}")

        for seed in args.seeds:
            _, text = build_seed_config(base_path, name, seed)
            new_path = out_dir / f"{name}_s{seed}.yaml"

            if args.dry_run:
                logger.info("[dry-run] would write %s", new_path.relative_to(repo))
            else:
                new_path.write_text(text)
                _verify(base_path, new_path, seed, name)
                logger.info("wrote %s", new_path.relative_to(repo))

            manifest.append(
                (new_path.relative_to(repo).as_posix(), f"{name}_s{seed}", runner),
            )

    if args.dry_run:
        return

    manifest_path = out_dir / "MANIFEST.tsv"
    manifest_path.write_text(
        "".join(f"{cfg}\t{name}\t{runner}\n" for cfg, name, runner in manifest),
    )
    logger.info("\nwrote %s (%d runs)", manifest_path.relative_to(repo), len(manifest))

    added = register_experiments(repo / "configs/experiments.yaml", manifest)
    logger.info(
        "registered %d new experiment(s) in configs/experiments.yaml", added,
    )

    n_train = sum(1 for _, _, r in manifest if r == "train")
    logger.info(
        "%d training runs x 5.27 h = %.0f GPU-hours (+%d untrained, minutes each)",
        n_train, n_train * 5.27, len(manifest) - n_train,
    )
    logger.info("\nLaunch with: bash scripts/run_seed_replicates.sh <shard_index> <num_shards> [gpu_id]")


if __name__ == "__main__":
    main()
